#!/bin/sh
#
# hostinfo-mach-factor-physical:
# show the hostinfo mach factor average per physical processor
#
# Syntax:
#
#     hostinfo-mach-factor-physical
#
# Example:
#
#     $ hostinfo-mach-factor-physical
#     4.80
#
#
# ## Tracking
#
#   * Command: hostinfo-mach-factor-physical
#   * Version: 1.0.0
#   * Created: 2017-11-01
#   * Updated: 2017-11-02
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
echo "scale=2; $(hostinfo-mach-factor) * $(hostinfo-processors-physical)" | bc -l