#!/bin/sh
#
# hostinfo-mach-factor-logical:
# show the hostinfo mach factor average per logical processor
#
# Syntax:
#
#     hostinfo-mach-factor-logical
#
# Example:
#
#     $ hostinfo-mach-factor-logical
#     9.60
#
#
# ## Tracking
#
#   * Command: hostinfo-mach-factor-logical
#   * Version: 1.0.0
#   * Created: 2017-11-01
#   * Updated: 2017-11-02
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
echo "scale=2; $(hostinfo-mach-factor) * $(hostinfo-processors-logical)" | bc -l