#!/bin/sh
#
# hostinfo-loadavg-physical:
# show the hostinfo load average per physical processor
#
# Syntax:
#
#     hostinfo-loadavg-physical
#
# Example:
#
#     $ hostinfo-loadavg-physical
#     0.60
#
#
# ## Tracking
#
#   * Command: hostinfo-loadavg-physical
#   * Version: 1.0.0
#   * Created: 2017-11-01
#   * Updated: 2017-11-02
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
echo "scale=2; $(hostinfo-loadavg) / $(hostinfo-processors-physical)" | bc -l