#!/bin/sh
#
# hostinfo-loadavg-logical:
# show the hostinfo loadavg per logical processor
#
# Syntax:
#
#     hostinfo-processor-type
#
# Example:
#
#     $ hostinfo-loadavg-logical
#     0.85
#
#
# ## Tracking
#
#   * Command: hostinfo-processor-type
#   * Version: 1.0.0
#   * Created: 2017-11-01
#   * Updated: 2017-11-02
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
hostinfo  | perl -e '
while(<>){ 
  $loadavg = $1 if /Load average: ([\d\.]+)/; 
  $processors = $1 if /^(\d+) processors are physically available/; 
} 
print $loadavg . "\n";
print $processors . "\n";
print $loadavg/$processors;
'
